# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-11-21 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_auto_20181118_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='is_accepted_by',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='priority',
            field=models.CharField(default=b'low', max_length=6),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='status',
            field=models.CharField(default=b'new', max_length=9),
        ),
    ]
