# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-11-22 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_auto_20181122_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='is_declined_by',
            field=models.CharField(default=b'-1,', max_length=200),
        ),
    ]
