# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-11-22 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_deliverytask_is_declined_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytask',
            name='is_accepted_by',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
