# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-11-24 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_auto_20181124_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytask',
            name='priority',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
