# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-11-24 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_auto_20181124_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='is_priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='priority',
            field=models.CharField(default=b'low', max_length=6),
        ),
    ]
