# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-11-24 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_auto_20181124_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytask',
            name='is_declined_by',
            field=models.CharField(default=b'-1', max_length=200),
        ),
    ]
