# Generated by Django 2.1.3 on 2018-12-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_auto_20181204_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='transition',
            field=models.CharField(default='new', max_length=1000),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='status',
            field=models.CharField(default='new', max_length=9),
        ),
    ]
